region = "us-east-2"
company = "MJCConsulting"
environment = "Production"
application = "App1"
hostname_prefix = "mjcue2papp1"
project = "Tutorial21"
domain = "x.mcrawford.mjcconsulting.com"
notification_email = "mcrawford@mjcconsulting.com"
